### PR TITLE
Fix typos in options.md

### PR DESCRIPTION
**Pull request by rikhuijzer**

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors merge

**Comment by rikhuijzer** [comment]
@DilumAluthge, sorry, I saw another typo. Can you review again?

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
