### PR TITLE
[Breaking] Remove the "pre-commit hooks" and "update manifests" features

### LINKED ISSUE #111: Idea: Update `Manifest.toml` files even when there is no change to `[compat]`
Consider this situation. Your `Project.toml` file looks like this:
```toml
[deps]
Foo = "uuid_for_foo_package"

[compat]
Foo = "2"
```

And your `Manifest.toml` file has `Foo` at version `2.0.0`.

Now suppose that `Foo` releases version `2.0.1`.

Your existing compat entry of `Foo = "2"` includes this new release `2.0.1`. So CompatHelper will not make an PR to bump your compat entry for `Foo`. After all, you don't need to bump your compat entry for `Foo`.

But, since you made the decision to check your `Manifest.toml` into source control, perhaps you would like to update your `Manifest.toml` file so that it has `Foo` at version `2.0.1` instead of version `2.0.0`?

I think we should have the option for CompatHelper to make a PR in these cases, so that you can keep your `Manifest.toml` files up-to-date even if your compat entries do not need to be bumped.

As with everything in CompatHelper, there will be a keyword argument that allows you to enable or disable this feature.

The question is: what should the default value be? Should this feature be enabled by default or disabled by default?

@christopher-dG @fredrikekre - Would love to get your input on this.

### LINKED ISSUE #170: Update Manifest.toml files with appropriate Julia versions
Now that CompatHelper updates all Manifest.toml by default, it would be great if it looks at `julia` compatibility bounds in Project.toml and uses appropriate binaries to do this (or alternatively Pkg.jl takes `julia` bound into account while `Pkg.update`).  ATM, it's very hard to support `julia` < 1.3 and >= 1.3 while making CI reproducible by checking in Manifest.toml file as many packages start dropping `julia` < 1.3 due to the new artifacts support.

I'm thinking to check in e.g. `test/environments/jl10/Manifest.toml` with `julia = "< 1.3"` in `Project.toml` so that I can still test it with Julia 1.0 via [`Run.test(project="test/environments/jl10")`](https://tkf.github.io/Run.jl/dev/#Run.script).  However this requires `test/environments/jl10/Manifest.toml` to be updated with `julia` 1.0 while `test/Manifest.toml` to be updated with the latest `julia`.

I suppose this would require Julia installer as a Julia package (e.g., using https://github.com/JuliaLang/julia/issues/33817) and/or distributing `julia` binaries as artifacts?

### LINKED ISSUE #172: Check upstream git repository
`Pkg.update` fails if the manifest is tracking the unregistered version (`add Upstream#master`) and the upstream bump the version.  It would be nice if CompatHelper checks the upstream git repositories if checked-in manifest files have the `repo-url` entry. Is it in the scope of CompatHelper?

### LINKED ISSUE #194: Update Manifest.toml files even if no Project.toml files are changed
Would be good for this to be an option.

### LINKED ISSUE #213: Are secrets accessible in build script of upstream packages executed during Pkg.update?
I haven't confirmed this, but, IIUC, `CompatHelper.main()` can call `Pkg.update` which can execute `deps/build.jl`. If so, I suppose this script has access to my secrets? How about decoupling "preparation" and "deploy" phases?  Maybe something like this?

```yaml
- name: CompatHelper.prepare()
  run: julia -e 'using CompatHelper; CompatHelper.prepare()'  # no access to secretes
- name: CompatHelper.deploy()
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}
  run: julia -e 'using CompatHelper; CompatHelper.deploy()' # only limited packages are loaded
```

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #111
Closes #170
Closes #172
Closes #194
Closes #213

## Summary

This pull request makes the following changes:
1. Remove the "pre-commit hook" functionality.
2. Remove the "update manifests" functionality.
3. Bump the version number from `1.x.y` to `2.0.0`, because this is a breaking change.

## Motivation

There are multiple reasons why I want to make this change:
1. Security concerns, e.g. #213. In order to update a manifest, we call `Pkg.update`. This means that package build code gets run as part of the CompatHelper job. In theory, a malicious package could add some build code that tries to steal secure environment variables such as `GITHUB_TOKEN`.
2. There are other (better) options for people that want to update their manifests. I won't make an exhaustive list here, but perhaps someone could make a Discourse post of all of the manifest-updater GitHub Actions.
3. It is out of scope of the original intention of CompatHelper. The original goal of CompatHelper was simply to bump `[compat]` entries in the `Project.toml` file when your dependencies make new breaking releases. In the spirit of "do one thing, and do it well", I'd like to focus on this core mission.
4. It causes CompatHelper to break if there is a "bad" `Manifest.toml` file in the repo. This can be quite confusing to users - why should CompatHelper break due to an unrelated `Manifest.toml` file?

## Future

I am not opposed to adding this functionality back, but we would need to fix the security first. For example, maybe we would run the `Pkg.update` inside some kind of secure sandbox that has restricted privileges and does not have access to any secure environment variables  such as `GITHUB_TOKEN`.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors merge

**Comment by ericphanson** [comment]
Until https://github.com/JuliaRegistries/CompatHelper.jl/pull/282 the suggested workflow wasn’t versioned, so I’d be pretty careful about breaking changes! It seems like this doesn’t break that workflow though, only custom ones, is that right?

**Comment by DilumAluthge** [comment]
Yeah, it will only break custom workflows that pass a custom precommit hook.

If people still need the precommit hook functionality, they will need to use CompatHelper v1.

I'll make a Discourse post asking people to update the CompatHelper workflow files.

**Comment by maleadt** [comment]
> * There are other (better) options for people that want to update their manifests. I won't make an exhaustive list here, but perhaps someone could make a Discourse post of all of the manifest-updater GitHub Actions.
> 
> * It is out of scope of the original intention of CompatHelper. The original goal of CompatHelper was simply to bump `[compat]` entries in the `Project.toml` file when your dependencies make new breaking releases. In the spirit of "do one thing, and do it well", I'd like to focus on this core mission.

re. these two points: in CUDA.jl I have the Manifest committed, and CI uses it. If CompatHelper now bumps the compat entries without updating the Manifest, I can't be sure that bump is safe because the CI run on that PR used an older Manifest. Sure, there's separate actions that update the Manifest, but that then happens in a different PR, so doesn't help here. Or am I missing something?

**Comment by DilumAluthge** [comment]
The short answer is that you can still use CompatHelper v1. Just copy the workflow file from https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/.github/workflows/CompatHelper.yml, and change the line that looks like `version = "2"` to be `version = "1"` instead.

The long answer has a couple different parts:

1. Even if you have a manifest checked in to source control, and even if CompatHelper updates the manifest, this does not guarantee that your test suite will run with the updated versions of dependencies. For example, suppose that your `[compat]` entry is `Foo = "0.1, 0.2"`. And suppose that the `Manifest.toml` file uses `Foo` version `0.2.0`. This does not guarantee that `Pkg.test` will use `Foo` version `0.2.0`. When you run `Pkg.test`, Pkg is allowed to re-resolve your dependencies. Therefore, `Pkg.test` is still allowed to use `Foo` version `0.1.0`. More discussion is available in https://github.com/JuliaLang/Pkg.jl/pull/2439 and https://github.com/JuliaLang/Pkg.jl/pull/2176. This issue has been solved on GitHub Actions; see https://github.com/JuliaRegistries/CompatHelper.jl/issues/160 for details of the fix. However, if you don't use GitHub Actions, you won't get this fix. At some point, we should think about adding this fix to Buildkite - basically, we would need to implement https://github.com/julia-actions/julia-runtest/pull/20 for Buildkite.
2. Honestly, I would be happy to add the "update manifests" feature back to CompatHelper. However, we need to figure out a secure way to do it. For example, when we run the `Pkg.update` function, we need to make sure of the following:
    - The process that runs `Pkg.update` does not have access to the `GITHUB_TOKEN` or `COMPATHELPER_PRIV` secure environment variables. Since processes can access the environment variables of any other process started by the same user, this also means that we need to somehow run this process under a different user.
    - The process that runs `Pkg.update` does not have access to SSH private keys, e.g. it doesn't have access to the `$HOME/.ssh` directory.

**Comment by DilumAluthge** [comment]
If we can get https://github.com/JuliaLang/Pkg.jl/pull/2504 merged, we can add the "update manifests" feature back to CompatHelper.

**Pull request merged**
