### PR TITLE
only try to remove tmp_dir if it's still there

### LINKED ISSUE #264: with_tmp_dir atexit hook fails
Hi,

I just noticed that the `atexit` hook fails for `with_tmp_dir` because the directory is already gone.
I think the problem is `walkdir` in `prepare_for_deletion` which throws an error by default if it can't `readdir` the directory.
Maybe providing a custom error handler to `walkdir` could fix this?

You can see the error e.g. in [this CompatHelper run](https://github.com/fkastner/NiceNumbers.jl/runs/1801953405?check_suite_focus=true).

### PR DESCRIPTION
**Pull request by fkastner**
This should fix #264.

### CODE REVIEW

**Comment by KristofferC** [comment]
`mktempdir` should do this by itself since 1.3 I think.

**Comment by fkastner** [comment]
So `with_tmp_dir` should probably be removed altogether and changed to `mktempdir`?

**Comment by KristofferC** [comment]
I would say so

**Comment by fkastner** [comment]
`mktempdir` has the `cleanup` keyword only since 1.3 but this package still supports 1.2.
Should support for 1.2 be dropped then? What would be the alternative strategy?

**Comment by KristofferC** [comment]
Personally, I don't really see a need to support 1.2 since this is just a bot that runs.

**Comment by fkastner** [comment]
I removed all calls to `rm` where the file/folder is created with `mktemp` or `mktempdir`. In particular the `atexit` hooks are gone now, too. In one case I changed from manually creating a file to using `mktemp` to avoid having to cleanup manually afterwards.

Also the `with_temp_dir` and also `prepare_for_deletion` were removed since they are no longer needed now.

**Comment by DilumAluthge** [comment]
I think #280 should fix all of these issues. Let me know if you still notice any issues after #280 is merged and a new release is registered.

**Pull request closed without merging**
