### PR TITLE
[DO NOT MERGE] Merge the `v3-dev` branch into the `master` branch

### PR DESCRIPTION
**Pull request by DilumAluthge**
Do not merge this PR. The only purposes of this PR are:
1. To make sure that there are no merge conflicts between `v3-dev` and `master`
2. To immediately fix merge conflicts between `v3-dev` and `master` as soon as they arise
3. To be able to run CI on merging `v3-dev` into `master` - just comment `bors try` on this PR

Note: the `DO NOT MERGE` label on this PR should be sufficient to prevent Bors from merging it.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors try

**Comment by fchorney** [comment]
At this point, how do we feel about unleashing this? Are there any more tests/etc that we want to do before slapping the new version up?

**Comment by DilumAluthge** [comment]
I say let's go for it.

I do anticipate that, once we register the v3.0 release, we will probably see some bugs pop up in production. So we should be ready to fix those pretty quickly.

**Comment by DilumAluthge** [comment]
Closing in favor of https://github.com/JuliaRegistries/CompatHelper.jl/pull/361

**Pull request closed without merging**
