### PR TITLE
Clarify the log message when the SSH deploy key is not found

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@ablaom Can you take a look and let me know if these log messages sound more clear?

**Review by ablaom — APPROVED** [review]
Looks good to me

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
