### PR TITLE
Clean slate for V3

### PR DESCRIPTION
**Pull request by mattBrzezinski**
## Note: This merge request is targeting the feature branch v3-dev

Removed all of the code except for boiler plate Julia stuff to have a clean slate to build `v3` of this package upon.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
I've made `v3-dev` a protected branch so that we can e.g. make sure that code coverage stays at 100% with each PR to `v3-dev`.

Once we are done making PRs to `v3-dev` and we are ready to merge `v3-dev` into `master`, I will remove the branch protections for `v3-dev`.

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Review by mattBrzezinski — COMMENTED** [review]
LGTM!

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
