### PR TITLE
Add flag for a short branch name

### PR DESCRIPTION
**Pull request by fchorney**
Hitting an issue where the branch names are too big for certain tests we are doing with AWS. This adds in a flag to use a shorter branch name.

### CODE REVIEW

**Comment by fchorney** [comment]
This may not be needed, as we are looking into other solutions.

**Comment by fchorney** [comment]
Nevermind, we found a different solution. Unless anyone else needs this I am going to close it.

**Comment by DilumAluthge** [comment]
> Nevermind, we found a different solution. Unless anyone else needs this I am going to close it.

SGTM.

Just out of curiosity, what was your solution?

**Comment by fchorney** [comment]
The issue was with role names, they must be 64 chars or smaller. We just opted to truncate them as that should be fine for our purposes

**Pull request closed without merging**
