### PR TITLE
Only clone once, not once per subdir

### LINKED ISSUE #442: Why clone once per subdir?
Seems like it could clone once and then re-use the clone for each subdir.

For me, for some reason the first clone goes through, and then the later ones hit
```
Cloning into 'REPO'...
Warning: Permanently added the ECDSA host key for IP address '140.82.112.4' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'REPO'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

### PR DESCRIPTION
**Pull request by ericphanson**
Closes https://github.com/JuliaRegistries/CompatHelper.jl/issues/442

This PR has two commits (+ formatting); the first lets tests pass locally on my machine, by specifying the `init-branch` instead of relying on it being set to `master`. The second does the change to close #442. Besides speeding things up and possibly avoiding weird cloning issues, this also makes the code more "compositional" and simplifies the tests.

edit: I've also pushed an additional commit to re-use the same local clone for each PR. It seems wasteful to make so many clones, and in #442 for some reason for me the first clone seems to work and the subsequent ones fail.

### CODE REVIEW

**Comment by ericphanson** [comment]
bors try

**Comment by ericphanson** [comment]
bors try

**Comment by ericphanson** [comment]
bors try

**Comment by lgoettgens** [comment]
What is the state of this? I would like to tackle https://github.com/JuliaRegistries/CompatHelper.jl/issues/408, but having this PR here as a baseline would make things a lot easier.

**Comment by ericphanson** [comment]
Just need review iirc

**Comment by lgoettgens** [comment]
maybe ping them again? After 10 months I find that reasonable

**Comment by ericphanson** [comment]
If I know my GitHub notifications these comments will do it :). Also I have merge rights so if you or anyone else wants to review, that would suffice for me to feel comfortable merging.

**Comment by fchorney** [comment]
Hey sorry, I have changed jobs this summer and am no longer working in Julia. I probably won't really have time to look at stuff like this going forward.

**Comment by mattBrzezinski** [comment]
> @fchorney or @mattBrzezinski Could you review this?

I'll put it on my TODO list, hopefully get around to it in a few days. Just busy with other things currently :(

**Comment by lgoettgens** [comment]
The docs failure will be resolved by https://github.com/JuliaRegistries/CompatHelper.jl/pull/453.

**Review by mattBrzezinski — APPROVED** [review]

**Comment by ericphanson** [comment]
bors merge

**Pull request merged**
