### PR TITLE
using package server to download registry

### LINKED ISSUE #209: CompatHelper doesn't respect package server
CompatHelper tries to clone registry even when `JULIA_PKG_SERVER` is set, specifically in
https://github.com/bcbi/CompatHelper.jl/blob/master/src/get_latest_version_from_registries.jl#L17 which leads to completely ignoring the set `JULIA_PKG_SERVER` variable.

### PR DESCRIPTION
**Pull request by racinmat**
Fixes #209 .

### CODE REVIEW

**Comment by racinmat** [comment]
@DilumAluthge  better now?

**Comment by DilumAluthge** [comment]
Thanks!

I'll do a more thorough review this week or next week.

**Comment by DilumAluthge** [comment]
bors try

**Comment by racinmat** [comment]
Sorry, typo, fixed.

**Comment by DilumAluthge** [comment]
bors try

**Comment by racinmat** [comment]
Sorry, another one. No more books.

**Comment by DilumAluthge** [comment]
bors try

**Comment by racinmat** [comment]
fixed

**Comment by DilumAluthge** [comment]
bors try

**Comment by racinmat** [comment]
I had probably some bad day, now it should pass.

**Comment by DilumAluthge** [comment]
bors try

**Comment by racinmat** [comment]
Any idea how to test this?

**Comment by DilumAluthge** [comment]
We can leave it untested for now.

I'll do one last review this week and then I'll merge.

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
bors merge

**Comment by DilumAluthge** [comment]
@racinmat Thanks for your patience!

**Comment by DilumAluthge** [comment]
bors merge

**Comment by fredrikekre** [comment]
> The reason I want to keep the default behavior as cloning over git is this: often, the pkg server does not serve the latest registry. For example, recently, it was serving a registry that was more than 2 hours old. So cloning over git is still the most reliable way to get the registry.

IMO that is an argument for having this default, now the PR that CompatHelper submits just fails instead, since the PkgServer is the default for CI.

**Comment by racinmat** [comment]
Wait, but PkgServer is not default for CI, this PR made in only possible to use it, as in opt-in if you add kwarg to `main` function. 
The default behavior has been left unchanged.

**Comment by KristofferC** [comment]
> Wait, but PkgServer is not default for CI, this PR made in only possible to use it, as in opt-in if you add kwarg to main function.

It is on Julia 1.5+

**Comment by racinmat** [comment]
Maybe we are talking about different things. Yes, Julia Pkg uses by default PkgServer on version 1.5+, but in CompatHelper there is explicit cloning: https://github.com/JuliaRegistries/CompatHelper.jl/blob/master/src/get_latest_version_from_registries.jl#L6
regardless of version.

**Comment by fredrikekre** [comment]
> CompatHelper there is explicit cloning

Yes, that is the problem -- I think this functionality that you implemented should be default.

**Comment by DilumAluthge** [comment]
> now the PR that CompatHelper submits just fails instead, since the PkgServer is the default for CI.

That's a good point

**Comment by DilumAluthge** [comment]
#252

**Comment by KristofferC** [comment]
There's also the problem that there are many pkg servers and they often don't serve the exact same copy of the registry.

**Pull request merged**
