### PR TITLE
By default, get the registry from the Pkg server

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
bors try

**Comment by fredrikekre** [comment]
Probably need to make it conditional on `VERSION.

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors try

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
